NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
g <- c(sum(NEI$Emissions[NEI$year==1999]),sum(NEI$Emissions[NEI$year==2002]),sum(NEI$Emissions[NEI$year==2005]),sum(NEI$Emissions[NEI$year==2008]))
h <- c(1999,2002,2005,2008)
png('plot1.png')
plot(h,g,xlab = "YEARS", ylab = "Total Emissions (in tons)", pch = 20)
lines(h,g, col = 'red', lwd = 2)
title(main = "PM2.5 Emissions")
dev.off()