NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
Baltimore <- subset(NEI, fips == "24510")
g <- c(sum(Baltimore$Emissions[Baltimore$year==1999]),sum(Baltimore$Emissions[Baltimore$year==2002]),sum(Baltimore$Emissions[Baltimore$year==2005]),sum(Baltimore$Emissions[Baltimore$year==2008]))
h <- c(1999,2002,2005,2008)
png('plot2.png')
plot(h,g,xlab = "YEARS", ylab = "Total Emissions (in tons)", pch = 20)
lines(h,g, col = 'red', lwd = 2)
title(main = "PM2.5 Emissions in Baltimore City")
dev.off()